import ME from "../assets/me.png"
const Data = [
  {
    id: 1,
    image:ME,
    title:'Something Something',
    github: 'https://gitub.com' ,
    demo: 'https://gitub.com',
  },
  {
    id: 2,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 3,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 4,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 5,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 6,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 7,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 8,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 9,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 10,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 11,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 12,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 13,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 14,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  },
  {
    id: 15,
    image:ME,
    title:'Something Something',
    github:'https://gitub.com',
    demo:'https://gitub.com',
  }
]

export default Data